// Generated by protoc-gen-js-mjs
// Source: test.proto

// Package: pokeworld.player.cs

// Enum: Status
export const Status = {
    UNKNOWN: 0,
    ACTIVE: 1,
    INACTIVE: 2,
};

// Message: Player
export class Player {
    static __descriptor = {
        name: "Player",
        fullName: "pokeworld.player.cs.Player",
    }

    /** @return {string} */
    getEntityInfo() {
        return this.entity_info;
    }

    /** @param {string} value */
    setEntityInfo(value) {
        this.entity_info = value;
    }

    /** @return {Status} */
    getEntityState() {
        return this.entity_state;
    }

    /** @param {Status} value */
    setEntityState(value) {
        this.entity_state = value;
    }

}

// Message: GetPlayersResponse
export class GetPlayersResponse {
    static __descriptor = {
        name: "GetPlayersResponse",
        fullName: "pokeworld.player.cs.GetPlayersResponse",
    }

    /** @return {Result[]} */
    getResults() {
        return this.results;
    }

    /** @param {Result[]} value */
    setResults(value) {
        this.results = value;
    }


    // Nested message: Result
    static Result = class {
        static __descriptor = {
            name: "Result",
            fullName: "pokeworld.player.cs.GetPlayersResponse.Result",
        }

        /** @return {boolean} */
        getSuccess() {
            return this.success;
        }

        /** @param {boolean} value */
        setSuccess(value) {
            this.success = value;
        }

        /** @return {number} */
        getEntityId() {
            return this.entity_id;
        }

        /** @param {number} value */
        setEntityId(value) {
            this.entity_id = value;
        }

        /** @return {Player} */
        getPlayer() {
            return this.player;
        }

        /** @param {Player} value */
        setPlayer(value) {
            this.player = value;
        }

    };

}

