// Generated by protoc-gen-js-mjs
// Source: test2.proto

// Package: pokeworld.player.cs

// Message: Entity
export class Entity {
    static __descriptor = {
        name: "Entity",
        fullName: "pokeworld.player.cs.Entity",
    }

    /** @return {string} */
    getName() {
        return this.name;
    }

    /** @param {string} value */
    setName(value) {
        this.name = value;
    }

}

